### ISSUE TITLE
Push mode

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#239]
- Add command line arguments to enable pushing of data from decentralized instances to central incident commander:
  `--upstream https://https://incident-commander.canary.lab.flanksource.com/ --upstream-user=admin@local --upstream-password=admin --upstream-labels="cluster=a"`

Use polling to push components, configs, analysis to centralized instance, injecting new labels as necessary

**Comment by adityathebe** [comment]
@moshloop can we close this?
