### ISSUE TITLE
Push Mode: Saving linked components and config items 

### ISSUE THREAD

**Issue by adityathebe** [flanksource/incident-commander#400]
Upserting some config items with parents results in this error.

`upstream reconcile job: failed to push missing resource ids: upstream server returned error status[500]: {"error":"error upserting config_items: ERROR: insert or update on table \"config_items\" violates foreign key constraint \"config_items_parent_id_fkey\" (SQLSTATE 23503)","message":"failed to upsert upstream message"}`

I suppose we need to incrementally store config items so the parents are always there when children are being inserted.
Same thing with components.

**Comment by moshloop** [comment]
@adityathebe  is this still an issue?

**Comment by adityathebe** [comment]
@moshloop no it's not.
