### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#428]
Ability to add custom notifications for:

* canary_pass, canary_fail, canary_transition
* incident.assign, create, resolve, close, comment
* definition_of_done.pass|fail|transition

* Can specify either an inline notification, or a team
* Label filtering
* Cel/Exprv based filtering of events.

**Comment by moshloop** [comment]
Destination can be a notification handler or a team

**Comment by adityathebe** [comment]
List of Events (draft)

## 1. check
- check.pass
- check.fail
- check.transition

**Env vars**
- check

## 2. incident
- incident.assign
- incident.create
- incident.resolve
- incident.close
- incident.comment

**Env vars**
- incident

## 2.1 responder
- incident.responder.added
- incident.responder.removed

**Env vars**
- responder

### 2.2 comment
- incident.comment.mention

**Env vars**
- mentionedUsers `<SetOf(mentioned users' emails)>`

### 2.3. definition of done
- incident.dod.pass
- incident.dod.fail
- incident.dod.transition

**Env vars**
- evidence
