### ISSUE TITLE
Notifications | We need to somehow make the users aware of any failures that occur when sending notifications

### ISSUE THREAD

**Issue by adityathebe** [flanksource/incident-commander#553]
Notification is in 2 phases
1. creating new `notification.send` events from other events
2. publishing the notification (queued in `notification.send`)

We only record errors to job history in the first step. More precisely only when expression evaluation fails. 

Errors when actually publishing the notifications are never saved to job history. This could happen for various reasons: bad API key, invalid recipient, a working API key expires, ...

**Comment by adityathebe** [comment]
@moshloop I think we should keep a job history of "notification sends".

Unlike, when creating a new `notification.send` event, where we only save to job history on failure, we could always save "notification sends" to job history. That indirectly solves [this issue](https://github.com/flanksource/incident-commander/issues/542) & more importantly also provides an audit trail of all notifications that were sent out.

**Comment by moshloop** [comment]
@adityathebe I think we should probably use a dedicated notification_history table for this.

**Comment by adityathebe** [comment]
@moshloop in that case, have you decided on what should be done for [this](https://github.com/flanksource/incident-commander/issues/542)

We have the option to 
- have one job history per notification. It's updated whether adding notification succeeds or fails. Or,
- have the status column in the `notifications` table itself.
