### ISSUE TITLE
api/playbook/list should only return name/icon/description

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#596]

**Comment by adityathebe** [comment]
@moshloop We do not have icon & description so I am only returning the id and name.
Although, doesn't it also need the spec? At least the parameters from spec?

![image](https://github.com/flanksource/incident-commander/assets/13419481/8eb811fc-b918-465b-8852-63de849d19e6)

**Comment by moshloop** [comment]
@adityathebe  - Ah we can probably just return it without the actions
